baseurl = "https://veith.github.io/flowbased-polymer/"
languageCode = "en-us"
title = "Flowbased Polymer"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-97538731-1"

[params]
	# General information
	author = "veith"
	description = "Flowbased Programming for web UIs."
	copyright = "Released under the MIT license"
    disqusShortname = "https-veith-github-io-flowbased-polymer"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/veith/flowbased-polymer"

	version = "3.1.*"
	logo = "images/logoorange.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "lime"
    	accent  = "teal"

    [params.font]
    	text = "Roboto"
    	code = "Ubuntu Mono"


[social]
	#twitter = "veith"
	github  = "veith"


[[menu.main]]
	name   = "Flowbased Polymer"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Installation"
	url    = "install/overview/"
	weight = 100

[[menu.main]]
	name   = "Getting started"
	url    = "wireing/overview/"
	weight = 200

[[menu.main]]
	name   = "Tutorial"
	url    = "tutorial/tutorial/"
	weight = 200

[[menu.main]]
	name   = "Firing Events"
	url    = "events/overview/"
	weight = 300

[[menu.main]]
	name   = "Using Properties"
	url    = "variables/overview/"
	weight = 400

[[menu.main]]
	name   = "Limitations"
	url    = "limitations/overview/"
	weight = 500

[[menu.main]]
	name   = "Best practices"
	url    = "bestpractice/overview/"
	weight = 600

[[menu.main]]
	name   = "Helper components"
	url    = "helper/overview/"
	weight = 700

[[menu.main]]
	name   = "License"
	url    = "license/index/"
	weight = 800


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
